name: CI

on:
  push:
    branches:
      - master
      - github-actions*
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  ci:
    name: CI
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Cargo registry
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-latest-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-latest-cargo-registry-
      - name: Cache Cargo index
        uses: actions/cache@v2
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-latest-cargo-index-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-latest-cargo-index-
      - name: Cache Cargo build
        uses: actions/cache@v2
        with:
          path: target/debug
          key: ${{ runner.os }}-latest-debug-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-latest-debug-target-

      - name: Test
        working-directory: tests
        run: |
          cc --version
          python3 --version
          rustc --version
          ./run_writer.sh
          python3 test_utils/test_runner.py
